### PR TITLE
Adds a manpage

### PR DESCRIPTION
**Pull request by trebmuh**
This commit adds a manpage: jalv.select.1
Please, check it in order to ensure that it fits with jalv.select.
Hope that helps.

### CODE REVIEW

**Comment by SpotlightKid** [comment]
Does the manpage need to have a GPL3 license? Since jalv.selct itself is in the Public Domain that's a bit arkward.

**Comment by brummer10** [comment]
Hi 
Indeed, it would be better to put the manpage as well under the Public Domain to avoid multiple licenses in the package. Also, some commands have changed recently.
Please check  here
https://github.com/brummer10/jalv_select/issues/16
and here 
https://github.com/brummer10/jalv_select/issues/13#issuecomment-202298883

**Comment by trebmuh** [comment]
Oh man, this one went totally under my radar!
I just updated the English man page and added a French translation of it.
Hope that helps.

**Comment by brummer10** [comment]
Many thanks Olivier

**Comment by trebmuh** [comment]
:+1:

**Pull request merged**
